#!/usr/bin/env bash
# Audio Tools Backup Wrapper
# Auto-generated by audio-tools installer

set -euo pipefail

# Configuration
CONFIG_FILE="{{CONFIG_FILE}}"
LOGS_DIR="{{LOGS_DIR}}"
RUN_EXTRACTION={{RUN_EXTRACTION}}

# Timestamp for logging
TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")

echo "[$TIMESTAMP] Starting audio-tools backup workflow..." | tee -a "$LOGS_DIR/workflow.log"

# Run backup based on configuration
echo "[$TIMESTAMP] Running backup..." | tee -a "$LOGS_DIR/workflow.log"
if {{AKAI_BACKUP_PATH}} batch >> "$LOGS_DIR/backup.log" 2>&1; then
  echo "[$TIMESTAMP] Backup completed successfully" | tee -a "$LOGS_DIR/workflow.log"
else
  echo "[$TIMESTAMP] Backup failed with exit code $?" | tee -a "$LOGS_DIR/workflow.log"
  exit 1
fi

# Run extraction if scheduled
if [ "$RUN_EXTRACTION" = "true" ]; then
  echo "[$TIMESTAMP] Running extraction..." | tee -a "$LOGS_DIR/workflow.log"
  if {{AKAI_EXTRACT_PATH}} batch >> "$LOGS_DIR/extraction.log" 2>&1; then
    echo "[$TIMESTAMP] Extraction completed successfully" | tee -a "$LOGS_DIR/workflow.log"
  else
    echo "[$TIMESTAMP] Extraction failed with exit code $?" | tee -a "$LOGS_DIR/workflow.log"
    exit 1
  fi
fi

echo "[$TIMESTAMP] Workflow completed successfully" | tee -a "$LOGS_DIR/workflow.log"
