name: akai-sampler-tools
version: 1.0.0
description: Akai sampler backup, extraction, and format conversion tools

technology_stack:
  languages:
    - TypeScript
    - JavaScript
  runtime:
    - Node.js
  tools:
    - pnpm (monorepo)
    - mtools (bundled)
    - akaitools (bundled)
    - rsnapshot
  frameworks:
    - Vitest (testing)

project_type: cli-utility

agents:
  # Core Development
  - orchestrator              # Workflow coordination
  - typescript-pro            # TypeScript expertise
  - javascript-pro            # Node.js/JavaScript expertise
  - cli-developer             # CLI interface design
  - build-engineer            # Binary bundling, cross-platform builds
  - backend-developer         # File operations, batch processing

  # Quality & Testing
  - code-reviewer             # Code quality and review
  - qa-expert                 # Testing strategy

  # Documentation & Infrastructure
  - documentation-engineer    # Documentation
  - devops-engineer           # Deployment, distribution, CI/CD
  - dependency-manager        # External tool dependencies

workflows:
  - main-workflow.yaml
  - feature-development.yaml
  - bug-fix.yaml
  - testing-workflow.yaml

features:
  - sampler_backup
  - disk_extraction
  - format_conversion
  - cross_platform_binaries
  - batch_processing

goals:
  - Zero-configuration installation on all platforms
  - Cross-platform binary bundling (< 5MB total)
  - Extraction success rate > 99%
  - User-friendly for non-technical musicians
