packages:
  - 'sampler-lib'
  - 'sampler-devices'
  - 'sampler-midi'
  - 'sampler-translate'
  - 'sampler-export'
  - 'sampler-backup'
  - 'lib-runtime'
  # sampler-interface excluded - UI app with missing dependencies
