//
// Created by Orion Letizi on 11/15/23.
//

#ifndef OL_DSP_CC_MAP_H
#define OL_DSP_CC_MAP_H

#define CC_REVERB_TIME 32
#define CC_REVERB_CUTOFF 33
#define CC_REVERB_BALANCE 34

#define CC_DELAY_TIME 35
#define CC_DELAY_FEEDBACK 36
#define CC_DELAY_CUTOFF 37
#define CC_DELAY_RESONANCE 38
#define CC_DELAY_BALANCE 39
#define CC_DELAY_FILTER_TYPE 40

#define CC_FILTER_CUTOFF 41
#define CC_FILTER_RESONANCE 42
#define CC_FILTER_TYPE 43
#define CC_FILTER_DRIVE 44

#define CC_EARLY_PREDELAY 50
#define CC_REVERB_TYPE 51
#define CC_REVERB_PREDELAY 52
#define CC_REVERB_PREFILTER 53
#define CC_REVERB_INPUT_DIFFUSION_1 54
#define CC_REVERB_INPUT_DIFFUSION_2 55
#define CC_REVERB_DECAY_DIFFUSION 56

#endif //OL_DSP_CC_MAP_H
